services:
  - type: web
    name: video-extractor-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: API_KEY
        value: your-secure-api-key-here
      - key: DEBUG_MODE
        value: false
